### ISSUE TITLE
Custom Hitnormal isn't detected if it doesn't belong to custom sampleset 1 

### ISSUE THREAD

**Issue by Kominaru** [MChecaH/ManiaCheck#5]
Title is self-explainatory. Bug can be reproduced by checking [Senpi - Last Boss Rush!!]: hitsound sampleset 5 is used, with hitnormal file correctly named `normal-hitnormal5.wav`, but it is not detected by the plugin. (https://osu.ppy.sh/beatmapsets/703004#mania/1487432) on MV, as of 19/9/22 versions of the map and plugin

Pic related:
![image](https://user-images.githubusercontent.com/43741444/191005922-8285442c-77fa-4414-819d-26ea2919444e.png)

**Comment by MChecaH** [comment]
This can literally be fixed by deleting 1 (one) dot in the Wildcard function used to detect Hitnormal samples in a folder.
![image](https://user-images.githubusercontent.com/93517213/209840042-cd6562b3-e71c-4d66-849e-de3d05626c24.png)

yeah.... I did that
