### ISSUE TITLE
No warning of missing hitnormal override if the Custom Sampleset option isn't selected in-game

### ISSUE THREAD

**Issue by Kominaru** [MChecaH/ManiaCheck#6]
The problem relies on the assumption "custom hitnormal in folder -> hitnormal is being overridden in the map": a hitnormal file may be present in the folder but not being used at all. 

The TimingPoints section of each .osu should be checked for this. 

Lines are of the form:
`1971,468.75,4,<sampleset>,<set_no>,75,1,0`

where `sampleset` ranges from 0 to 3 (auto, normal, soft, drum), and `set_no` indicates the sampleset number

`set_no` `0` is the default sampleset and should always warn about default sampleset usage. 
`set_no` `1` and above are custom samplesets 

e.g. for a line 

`1971,468.75,4,3,67,75,1,0`

the plugin should check for the existence of `drum-hitnormal67` in the folder and give an error if it does not exist.

**Comment by MChecaH** [comment]
3dcb4849329ae1e7453d4522f211488a4c4a5729 This should've fixed it. It now follows the detection algorithm you've suggested.
